// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZrI2xoya-EPsQSZ59Ej4KIUOnWHURTc',
    appId: '1:99988229819:android:6e5e6bf8609747684ca39e',
    messagingSenderId: '99988229819',
    projectId: 'cycle-fit-db',
    storageBucket: 'cycle-fit-db.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARWZ6rLxUKleqTyVfYK3psyjnVJFo2l-A',
    appId: '1:99988229819:web:27e85f334fd4d8ce4ca39e',
    messagingSenderId: '99988229819',
    projectId: 'cycle-fit-db',
    authDomain: 'cycle-fit-db.firebaseapp.com',
    storageBucket: 'cycle-fit-db.firebasestorage.app',
    measurementId: 'G-1K6RH8RC8T',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARWZ6rLxUKleqTyVfYK3psyjnVJFo2l-A',
    appId: '1:99988229819:web:eebadbd0de0705954ca39e',
    messagingSenderId: '99988229819',
    projectId: 'cycle-fit-db',
    authDomain: 'cycle-fit-db.firebaseapp.com',
    storageBucket: 'cycle-fit-db.firebasestorage.app',
    measurementId: 'G-9X3RECN0LM',
  );

}